// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Datas;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302162939_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inventory_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Category = "Accessories",
                            Code = "f230fh0g3",
                            Description = "Product Description",
                            Image = "bamboo-watch.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Bamboo Watch",
                            Price = 65m,
                            Quantity = 24,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1001,
                            Category = "Accessories",
                            Code = "nvklal433",
                            Description = "Product Description",
                            Image = "black-watch.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Black Watch",
                            Price = 72m,
                            Quantity = 61,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1002,
                            Category = "Fitness",
                            Code = "zz21cz3c1",
                            Description = "Product Description",
                            Image = "blue-band.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Blue Band",
                            Price = 79m,
                            Quantity = 2,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1003,
                            Category = "Clothing",
                            Code = "244wgerg2",
                            Description = "Product Description",
                            Image = "blue-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Blue T-Shirt",
                            Price = 29m,
                            Quantity = 25,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1004,
                            Category = "Accessories",
                            Code = "h456wer53",
                            Description = "Product Description",
                            Image = "bracelet.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Bracelet",
                            Price = 15m,
                            Quantity = 73,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1005,
                            Category = "Accessories",
                            Code = "av2231fwg",
                            Description = "Product Description",
                            Image = "brown-purse.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Brown Purse",
                            Price = 120m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1006,
                            Category = "Accessories",
                            Code = "bib36pfvm",
                            Description = "Product Description",
                            Image = "chakra-bracelet.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Chakra Bracelet",
                            Price = 32m,
                            Quantity = 5,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1007,
                            Category = "Accessories",
                            Code = "mbvjkgip5",
                            Description = "Product Description",
                            Image = "galaxy-earrings.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Galaxy Earrings",
                            Price = 34m,
                            Quantity = 23,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1008,
                            Category = "Electronics",
                            Code = "vbb124btr",
                            Description = "Product Description",
                            Image = "game-controller.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Game Controller",
                            Price = 99m,
                            Quantity = 2,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1009,
                            Category = "Electronics",
                            Code = "cm230f032",
                            Description = "Product Description",
                            Image = "gaming-set.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Gaming Set",
                            Price = 299m,
                            Quantity = 63,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1010,
                            Category = "Accessories",
                            Code = "plb34234v",
                            Description = "Product Description",
                            Image = "gold-phone-case.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Gold Phone Case",
                            Price = 24m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1011,
                            Category = "Electronics",
                            Code = "4920nnc2d",
                            Description = "Product Description",
                            Image = "green-earbuds.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Green Earbuds",
                            Price = 89m,
                            Quantity = 23,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1012,
                            Category = "Clothing",
                            Code = "250vm23cc",
                            Description = "Product Description",
                            Image = "green-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Green T-Shirt",
                            Price = 49m,
                            Quantity = 74,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1013,
                            Category = "Clothing",
                            Code = "fldsmn31b",
                            Description = "Product Description",
                            Image = "grey-t-shirt.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Grey T-Shirt",
                            Price = 48m,
                            Quantity = 0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1014,
                            Category = "Electronics",
                            Code = "waas1x2as",
                            Description = "Product Description",
                            Image = "headphones.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Headphones",
                            Price = 175m,
                            Quantity = 8,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1015,
                            Category = "Clothing",
                            Code = "vb34btbg5",
                            Description = "Product Description",
                            Image = "light-green-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Light Green T-Shirt",
                            Price = 49m,
                            Quantity = 34,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1016,
                            Category = "Fitness",
                            Code = "k8l6j58jl",
                            Description = "Product Description",
                            Image = "lime-band.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Lime Band",
                            Price = 79m,
                            Quantity = 12,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1017,
                            Category = "Clothing",
                            Code = "v435nn85n",
                            Description = "Product Description",
                            Image = "mini-speakers.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Mini Speakers",
                            Price = 85m,
                            Quantity = 42,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1018,
                            Category = "Accessories",
                            Code = "09zx9c0zc",
                            Description = "Product Description",
                            Image = "painted-phone-case.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Painted Phone Case",
                            Price = 56m,
                            Quantity = 41,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1019,
                            Category = "Fitness",
                            Code = "mnb5mb2m5",
                            Description = "Product Description",
                            Image = "pink-band.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Pink Band",
                            Price = 79m,
                            Quantity = 63,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1020,
                            Category = "Accessories",
                            Code = "r23fwf2w3",
                            Description = "Product Description",
                            Image = "pink-purse.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Pink Purse",
                            Price = 110m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1021,
                            Category = "Fitness",
                            Code = "pxpzczo23",
                            Description = "Product Description",
                            Image = "purple-band.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Purple Band",
                            Price = 79m,
                            Quantity = 6,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1022,
                            Category = "Accessories",
                            Code = "2c42cb5cb",
                            Description = "Product Description",
                            Image = "purple-gemstone-necklace.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Purple Gemstone Necklace",
                            Price = 45m,
                            Quantity = 62,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1023,
                            Category = "Clothing",
                            Code = "5k43kkk23",
                            Description = "Product Description",
                            Image = "purple-t-shirt.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Purple T-Shirt",
                            Price = 49m,
                            Quantity = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1024,
                            Category = "Clothing",
                            Code = "lm2tny2k4",
                            Description = "Product Description",
                            Image = "shoes.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Shoes",
                            Price = 64m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1025,
                            Category = "Clothing",
                            Code = "nbm5mv45n",
                            Description = "Product Description",
                            Image = "sneakers.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Sneakers",
                            Price = 78m,
                            Quantity = 52,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1026,
                            Category = "Clothing",
                            Code = "zx23zc42c",
                            Description = "Product Description",
                            Image = "teal-t-shirt.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Teal T-Shirt",
                            Price = 49m,
                            Quantity = 3,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1027,
                            Category = "Electronics",
                            Code = "acvx872gc",
                            Description = "Product Description",
                            Image = "yellow-earbuds.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yellow Earbuds",
                            Price = 89m,
                            Quantity = 35,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1028,
                            Category = "Fitness",
                            Code = "tx125ck42",
                            Description = "Product Description",
                            Image = "yoga-mat.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yoga Mat",
                            Price = 20m,
                            Quantity = 15,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1029,
                            Category = "Fitness",
                            Code = "gwuby345v",
                            Description = "Product Description",
                            Image = "yoga-set.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yoga Set",
                            Price = 20m,
                            Quantity = 25,
                            Rating = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
